[IMP][14.0] Module: pattern_import_export add domain for sub patterns
shopinvader/pattern-import-export pull request #107
Opened 2022-06-15 11:23 UTC by Kev-Roche

Add domain on sub patterns
replace : https://github.com/shopinvader/pattern-import-export/pull/83

2022-06-15 12:02 UTC, florian-dacosta requested changes

2022-06-15 12:02 UTC, florian-dacosta commented on pattern_import_export/models/ir_exports_line.py
> +            # if export_line.name and export_line.export_id.model_id.model:
You can totally remove this line now, not need to keep some old not working lines even comented

2022-06-15 12:02 UTC, florian-dacosta commented on pattern_import_export/views/pattern_config.xml
> +                    domain="[('model_id', '=', related_model_name)]"
This is not related_model_name here but related_model_id

2022-06-15 12:02 UTC, florian-dacosta commented on pattern_import_export/views/pattern_config.xml
> -                <field name="related_model_name" invisible="1" />
no need to deplace the field, it make a useless diff

2022-06-15 14:02 UTC, Kev-Roche commented
@florian-dacosta , my bad, I fix it

2022-06-15 14:04 UTC, florian-dacosta approved these changes

2022-06-25 10:04 UTC, kevinkhao approved these changes
functional tests
LGTM

2022-06-25 10:10 UTC, kevinkhao requested changes
spoke too soon: this only works if we test with the first field. If the field is on 2nd level or more, the problem persists:
![Screenshot from 2022-06-25 13-07-47](https://user-images.githubusercontent.com/19902174/175769050-3805d7f6-c165-45e3-8901-5150016e0bab.png)

2022-06-25 10:16 UTC, kevinkhao approved these changes

2022-08-22 13:02 UTC, bealdav commented
Finally many unmerged PR by there. Which are the PSC ? @sebastienbeau

2022-10-13 09:31 UTC, sebastienbeau commented
/ocabot merge patch

2022-10-13 09:34 UTC, merged