[14.0][FIX] pattern_import_export right for user to export
shopinvader/pattern-import-export pull request #115
Opened 2023-02-16 08:25 UTC by Kev-Roche

Actually, exporting a pattern requires write access on pattern.config but only pattern manager can, not pattern user. 
This PR add write right on pattern.config for pattern user group.

2023-02-26 14:36 UTC, sebastienbeau commented
We should not add the access right for basic user, to discuss

2023-03-06 15:18 UTC, Kev-Roche commented
@sebastienbeau, I remove the write right and add sudo() on pattern creation like you suggested

2023-04-03 07:25 UTC, sebastienbeau requested changes

2023-04-03 07:25 UTC, sebastienbeau commented on pattern_import_export/models/pattern_config.py
> +            self.env["pattern.file"]
We should not add a sudo here. Creation should be done without sudo.
In think the issue is on computed field that should be run with "compute_sudo=True"

2023-05-15 12:31 UTC, bealdav approved these changes

2023-05-23 20:44 UTC, sebastienbeau approved these changes

2023-05-23 20:44 UTC, sebastienbeau commented
/ocabot merge patch

2023-06-01 06:28 UTC, merged